name: release.yml
on:
  push:
    branches:
      - master

jobs:
  build_cpp:
    name: build cpp
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: msvc
          vcvarsall: true

          cmake: 4.2.2
          ninja: true
          vcpkg: false
          ccache: false
          clangtidy: false
          conan: true


          cppcheck: false

          gcovr: false
          opencppcoverage: false

      - uses: actions/cache@v5
        with:
          key: win-msvc-lua
          path: |
            S5DebugAdaptor/luapp/lua
            ~/.conan2/p

      - name: setup lua
        run:
          ./setup_lua.bat

      - name: Get dependency provider
        uses: dice-group/cpp-conan-release-reusable-workflow/.github/actions/add_conan_provider@main

      - name: Configure CMake
        run: |
          cmake -S . -B ./build "-DCMAKE_BUILD_TYPE=Release" -A Win32 -DCMAKE_SYSTEM_PROCESSOR=X86 "-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake"

      - name: Build
        run: |
          cmake --build ./build --parallel 4

      - name: release dir
        run: |
          mkdir ./Release
          cp /build/LuaDebugger.dll /Release/LuaDebugger.dll
          cp /build/LuaDebugger.pdb /Release/LuaDebugger.pdb

      - uses: actions/upload-artifact@v4
        with:
          path: ./Release
          name: debugger_dll
          overwrite: true

  
  buildExtension:
    name: Build VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v6

      - name: Install NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: '>=v21.21.1'
      
      - name: Build
        run: |
          cd extension
          npm run startpackagepipeline

      - name: package
        run: |
          mkdir ext
          EXTVER="$(jq ".version" extension/package.json | tail -c +2 | head -c -2)"
          cp ./extension/S5LuaDebuggerAdaptor-${EXTVER}.vsix ./ext/S5LuaDebuggerAdaptor-${EXTVER}.vsix
          echo ${EXTVER} > ext/debuggerlatestextension.txt

      - uses: actions/upload-artifact@v4
        with:
          path: ./ext
          name: extension
          overwrite: true


  release:
    name: release
    runs-on: ubuntu-latest
    needs:
      - build_cpp
      - buildExtension
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v7
        with:
          name: debugger_dll
          path: ./Release

      - uses: actions/download-artifact@v7
        with:
          name: extension
          path: ./ext

      - name: zip release
        run: |
          sudo apt install zip
          cd ./Release
          zip -r ../Release.zip .
          cd ../
          
          echo "EXT_VER=$(jq ".version" extension/package.json | tail -c +2 | head -c -2)" >> $GITHUB_ENV
          
          wget https://github.com/mcb5637/S5Updater/releases/download/nightly/HashFileBuilder
          chmod u+x HashFileBuilder 
          ./HashFileBuilder LuaDebuggerFile.dll ./Release/LuaDebugger.dll > ./debuggerhashes.txt

      - name: Delete tag
        run: gh release delete nightly --cleanup-tag -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v2
        with:
          body: "latest code from master"
          prerelease: true
          files: |
            ./Release.zip
            ./ext/S5LuaDebuggerAdaptor-${{ env.EXT_VER }}.vsix
            ./ext/debuggerlatestextension.txt
            ./debuggerhashes.txt
          name: nightly
          tag_name: nightly
          fail_on_unmatched_files: true
          target_commitish: master
          generate_release_notes: false
          append_body: false
          make_latest: false