name: try_update_extension.yml
on:
  workflow_dispatch:
      inputs:
        update_select:
          required: false
          default: ""
          type: string

jobs:
  build_cpp:
    name: try update VSCode Extension
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Repository
        uses: actions/checkout@v6

      - name: Install NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: '>=v21.21.1'

      - name: update
        run: |
          cd extension
          npm update ${{ inputs.update_select }}

      - name: Build
        run: |
          cd extension
          npm run startpackagepipeline

      - name: commit
        run: |
          git add extension/package.json
          git add extension/package-lock.json
          git commit -m "dependency update"
          git push
